<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class DoctorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $doctors = [
            [
                'name' => 'Dr. Sarah Johnson',
                'email' => 'sarah.johnson@doctorappoint.com',
                'password' => Hash::make('doctor123'),
                'phone' => '+1-555-0101',
                'address' => '123 Medical Plaza, Suite 100, New York, NY 10001',
                'role' => 'doctor',
                'specialization' => 'Cardiology',
                'bio' => 'Dr. Sarah Johnson is a board-certified cardiologist with over 15 years of experience in treating cardiovascular diseases. She specializes in preventive cardiology, heart failure management, and interventional procedures. Dr. Johnson is committed to providing personalized care and helping patients achieve optimal heart health.',
                'license_number' => 'MD-NY-12345',
                'years_of_experience' => 15,
                'consultation_fee' => 200.00,
                'profile_image' => '/images/doctors/sarah-johnson.jpg',
                'is_active' => true,
            ],
            [
                'name' => 'Dr. Michael Chen',
                'email' => 'michael.chen@doctorappoint.com',
                'password' => Hash::make('doctor123'),
                'phone' => '+1-555-0102',
                'address' => '456 Health Center, Floor 3, Los Angeles, CA 90001',
                'role' => 'doctor',
                'specialization' => 'Pediatrics',
                'bio' => 'Dr. Michael Chen is a dedicated pediatrician who has been caring for children and adolescents for over 12 years. He has expertise in childhood development, vaccinations, and managing acute and chronic pediatric conditions. Dr. Chen believes in building strong relationships with families to ensure the best care for every child.',
                'license_number' => 'MD-CA-23456',
                'years_of_experience' => 12,
                'consultation_fee' => 150.00,
                'profile_image' => '/images/doctors/michael-chen.jpg',
                'is_active' => true,
            ],
            [
                'name' => 'Dr. Emily Rodriguez',
                'email' => 'emily.rodriguez@doctorappoint.com',
                'password' => Hash::make('doctor123'),
                'phone' => '+1-555-0103',
                'address' => '789 Wellness Avenue, Suite 200, Chicago, IL 60601',
                'role' => 'doctor',
                'specialization' => 'Dermatology',
                'bio' => 'Dr. Emily Rodriguez is a skilled dermatologist with 10 years of experience in medical and cosmetic dermatology. She treats a wide range of skin conditions including acne, eczema, psoriasis, and skin cancer. Dr. Rodriguez is passionate about helping patients achieve healthy, beautiful skin through evidence-based treatments.',
                'license_number' => 'MD-IL-34567',
                'years_of_experience' => 10,
                'consultation_fee' => 180.00,
                'profile_image' => '/images/doctors/emily-rodriguez.jpg',
                'is_active' => true,
            ],
            [
                'name' => 'Dr. James Wilson',
                'email' => 'james.wilson@doctorappoint.com',
                'password' => Hash::make('doctor123'),
                'phone' => '+1-555-0104',
                'address' => '321 Medical Tower, Suite 500, Houston, TX 77001',
                'role' => 'doctor',
                'specialization' => 'Orthopedics',
                'bio' => 'Dr. James Wilson is an experienced orthopedic surgeon specializing in sports medicine and joint replacement. With 18 years of practice, he has performed thousands of successful surgeries and helped countless patients regain mobility and return to active lifestyles. Dr. Wilson uses the latest minimally invasive techniques for faster recovery.',
                'license_number' => 'MD-TX-45678',
                'years_of_experience' => 18,
                'consultation_fee' => 220.00,
                'profile_image' => '/images/doctors/james-wilson.jpg',
                'is_active' => true,
            ],
            [
                'name' => 'Dr. Lisa Anderson',
                'email' => 'lisa.anderson@doctorappoint.com',
                'password' => Hash::make('doctor123'),
                'phone' => '+1-555-0105',
                'address' => '654 Care Center, Floor 2, Miami, FL 33101',
                'role' => 'doctor',
                'specialization' => 'Obstetrics and Gynecology',
                'bio' => 'Dr. Lisa Anderson is a compassionate OB-GYN with 14 years of experience in women\'s health. She provides comprehensive care including prenatal care, family planning, and treatment of gynecological conditions. Dr. Anderson is dedicated to supporting women through all stages of life with personalized, evidence-based care.',
                'license_number' => 'MD-FL-56789',
                'years_of_experience' => 14,
                'consultation_fee' => 190.00,
                'profile_image' => '/images/doctors/lisa-anderson.jpg',
                'is_active' => true,
            ],
            [
                'name' => 'Dr. Robert Taylor',
                'email' => 'robert.taylor@doctorappoint.com',
                'password' => Hash::make('doctor123'),
                'phone' => '+1-555-0106',
                'address' => '987 Health Plaza, Suite 300, Boston, MA 02101',
                'role' => 'doctor',
                'specialization' => 'Neurology',
                'bio' => 'Dr. Robert Taylor is a board-certified neurologist with 20 years of experience in diagnosing and treating neurological disorders. He specializes in headaches, epilepsy, stroke, and movement disorders. Dr. Taylor stays at the forefront of neurological research to provide his patients with the most advanced treatment options.',
                'license_number' => 'MD-MA-67890',
                'years_of_experience' => 20,
                'consultation_fee' => 250.00,
                'profile_image' => '/images/doctors/robert-taylor.jpg',
                'is_active' => true,
            ],
            [
                'name' => 'Dr. Maria Garcia',
                'email' => 'maria.garcia@doctorappoint.com',
                'password' => Hash::make('doctor123'),
                'phone' => '+1-555-0107',
                'address' => '147 Medical Building, Suite 400, Phoenix, AZ 85001',
                'role' => 'doctor',
                'specialization' => 'Psychiatry',
                'bio' => 'Dr. Maria Garcia is a compassionate psychiatrist with 11 years of experience in mental health care. She specializes in treating depression, anxiety, bipolar disorder, and PTSD. Dr. Garcia uses a holistic approach combining medication management with psychotherapy to help patients achieve mental wellness.',
                'license_number' => 'MD-AZ-78901',
                'years_of_experience' => 11,
                'consultation_fee' => 175.00,
                'profile_image' => '/images/doctors/maria-garcia.jpg',
                'is_active' => true,
            ],
            [
                'name' => 'Dr. David Kim',
                'email' => 'david.kim@doctorappoint.com',
                'password' => Hash::make('doctor123'),
                'phone' => '+1-555-0108',
                'address' => '258 Clinic Center, Floor 1, Seattle, WA 98101',
                'role' => 'doctor',
                'specialization' => 'Ophthalmology',
                'bio' => 'Dr. David Kim is a skilled ophthalmologist with 13 years of experience in eye care and surgery. He specializes in cataract surgery, LASIK, and treatment of retinal diseases. Dr. Kim is committed to preserving and improving his patients\' vision using state-of-the-art technology and surgical techniques.',
                'license_number' => 'MD-WA-89012',
                'years_of_experience' => 13,
                'consultation_fee' => 195.00,
                'profile_image' => '/images/doctors/david-kim.jpg',
                'is_active' => true,
            ],
            [
                'name' => 'Dr. Jennifer Brown',
                'email' => 'jennifer.brown@doctorappoint.com',
                'password' => Hash::make('doctor123'),
                'phone' => '+1-555-0109',
                'address' => '369 Medical Complex, Suite 250, Denver, CO 80201',
                'role' => 'doctor',
                'specialization' => 'Endocrinology',
                'bio' => 'Dr. Jennifer Brown is an endocrinologist with 9 years of experience specializing in diabetes, thyroid disorders, and hormonal imbalances. She takes a patient-centered approach to help individuals manage their conditions and improve their quality of life through personalized treatment plans and lifestyle modifications.',
                'license_number' => 'MD-CO-90123',
                'years_of_experience' => 9,
                'consultation_fee' => 185.00,
                'profile_image' => '/images/doctors/jennifer-brown.jpg',
                'is_active' => true,
            ],
            [
                'name' => 'Dr. Thomas Martinez',
                'email' => 'thomas.martinez@doctorappoint.com',
                'password' => Hash::make('doctor123'),
                'phone' => '+1-555-0110',
                'address' => '741 Health Institute, Floor 4, Atlanta, GA 30301',
                'role' => 'doctor',
                'specialization' => 'General Surgery',
                'bio' => 'Dr. Thomas Martinez is a highly skilled general surgeon with 16 years of experience performing a wide range of surgical procedures. He specializes in minimally invasive laparoscopic surgery, hernia repair, and gastrointestinal surgery. Dr. Martinez is known for his precision, compassion, and excellent patient outcomes.',
                'license_number' => 'MD-GA-01234',
                'years_of_experience' => 16,
                'consultation_fee' => 210.00,
                'profile_image' => '/images/doctors/thomas-martinez.jpg',
                'is_active' => true,
            ],
            [
                'name' => 'Dr. Amanda White',
                'email' => 'amanda.white@doctorappoint.com',
                'password' => Hash::make('doctor123'),
                'phone' => '+1-555-0111',
                'address' => '852 Care Facility, Suite 150, Portland, OR 97201',
                'role' => 'doctor',
                'specialization' => 'Family Medicine',
                'bio' => 'Dr. Amanda White is a family medicine physician with 8 years of experience providing comprehensive care for patients of all ages. She focuses on preventive care, chronic disease management, and building long-term relationships with families. Dr. White believes in treating the whole person, not just symptoms.',
                'license_number' => 'MD-OR-12340',
                'years_of_experience' => 8,
                'consultation_fee' => 140.00,
                'profile_image' => '/images/doctors/amanda-white.jpg',
                'is_active' => true,
            ],
            [
                'name' => 'Dr. Christopher Lee',
                'email' => 'christopher.lee@doctorappoint.com',
                'password' => Hash::make('doctor123'),
                'phone' => '+1-555-0112',
                'address' => '963 Medical Park, Suite 350, San Diego, CA 92101',
                'role' => 'doctor',
                'specialization' => 'Pulmonology',
                'bio' => 'Dr. Christopher Lee is a pulmonologist with 7 years of experience specializing in respiratory diseases. He treats conditions such as asthma, COPD, pneumonia, and sleep disorders. Dr. Lee is dedicated to helping patients breathe easier and improve their lung health through advanced diagnostic and treatment methods.',
                'license_number' => 'MD-CA-23401',
                'years_of_experience' => 7,
                'consultation_fee' => 170.00,
                'profile_image' => '/images/doctors/christopher-lee.jpg',
                'is_active' => true,
            ],
        ];

        foreach ($doctors as $doctor) {
            User::create($doctor);
        }

        $this->command->info('✅ 12 doctors created successfully!');
        $this->command->info('   - All doctors are active');
        $this->command->info('   - Default password: doctor123');
    }
}
